# -*- coding: utf-8 -*-
r"""
GTI STEP3-2 REBUILD v1
======================

Purpose
-------
STEP2 collects broadly for up to 72 hours.
STEP3-2 keeps only recent customs/trade-policy news for STEP4 Gemini review.

Inputs
------
C:\Temp\2-1.naver_news_raw.xlsx
C:\Temp\2-2.google_news_raw.xlsx
C:\Temp\2-3.rss_news_raw.xlsx
C:\Temp\keyword.xlsx

Outputs
-------
C:\Temp\3-2.news_summary.xlsx
C:\Temp\3-2.news_cumulative.xlsx
C:\Temp\3-2.news_excluded.xlsx
C:\Temp\3-2.news_cluster_audit.xlsx

Core design
-----------
1. Strict published-date window (default 24h)
2. Article evidence only: title/summary/publisher/source
   - InputKeyword is NEVER used as relevance evidence
3. Strong customs signal => CORE
4. Strong trade-policy combination => CONTEXTUAL
5. Generic economy/industry/business noise => reject
6. Deduplicate by normalized URL/title
7. Cluster same policy event
8. Compare only against CLEAN cumulative generated by this rebuilt engine
9. No forced minimum count. Quality first.
10. Final output maximum 300 rows.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import time
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlparse, urlunparse

import pandas as pd
import requests


# =============================================================================
# CONFIG
# =============================================================================

BASE_DIR = Path(os.getenv("GTI_BASE_DIR", r"C:\Temp"))

INPUT_FILES = [
    BASE_DIR / "2-1.naver_news_raw.xlsx",
    BASE_DIR / "2-2.google_news_raw.xlsx",
    BASE_DIR / "2-3.rss_news_raw.xlsx",
]

KEYWORD_FILE = BASE_DIR / "keyword.xlsx"

OUTPUT_FILE = BASE_DIR / "3-2.news_summary.xlsx"
CUMULATIVE_FILE = BASE_DIR / "3-2.news_cumulative.xlsx"
EXCLUDED_FILE = BASE_DIR / "3-2.news_excluded.xlsx"
CLUSTER_AUDIT_FILE = BASE_DIR / "3-2.news_cluster_audit.xlsx"

ENGINE_VERSION = "GTI_STEP3_2_REBUILD_V1"

REPORT_HOURS = int(os.getenv("GTI_STEP3_RECENT_HOURS", "24"))
MAX_OUTPUT = int(os.getenv("GTI_STEP3_TARGET_MAX", "300"))
MAX_PER_CLUSTER = int(os.getenv("GTI_STEP3_CLUSTER_KEEP", "2"))

RESOLVE_ORIGINAL_URL = os.getenv("GTI_STEP3_RESOLVE_URL", "Y").upper() == "Y"
URL_TIMEOUT = int(os.getenv("GTI_STEP3_URL_TIMEOUT", "8"))
URL_RESOLVE_LIMIT = int(os.getenv("GTI_STEP3_URL_RESOLVE_LIMIT", "120"))

# A legacy cumulative from the old engine can poison the new selector.
# It is automatically archived and ignored unless it carries this engine version.
RESET_LEGACY_CUMULATIVE = os.getenv("GTI_STEP3_RESET_LEGACY_CUMULATIVE", "Y").upper() == "Y"


# =============================================================================
# VOCABULARY
# =============================================================================

STRONG_RULES = {
    "TARIFF": [
        "관세", "관세율", "상호관세", "추가관세", "수입관세", "수출관세",
        "tariff", "tariffs", "customs duty", "import duty", "export duty",
        "reciprocal tariff", "additional tariff",
        "section 232", "section 301", "232조", "301조",
    ],
    "CUSTOMS": [
        "통관", "세관", "수입신고", "수출신고", "관세평가", "과세가격",
        "보세", "관세환급", "특송물품", "소액면세",
        "customs", "customs clearance", "customs declaration",
        "customs valuation", "bonded warehouse", "de minimis",
    ],
    "HS_CLASSIFICATION": [
        "품목분류", "hs code", "hs코드", "tariff classification",
        "harmonized system",
    ],
    "ORIGIN_FTA": [
        "원산지", "원산지증명", "협정세율", "특혜관세",
        "fta", "cepa", "rcep", "usmca",
        "rules of origin", "certificate of origin", "preferential tariff",
    ],
    "AD_CVD": [
        "반덤핑", "덤핑방지관세", "상계관세", "무역구제",
        "anti-dumping", "anti dumping", "antidumping",
        "countervailing", "countervailing duty", "ad/cvd",
    ],
    "SAFEGUARD": [
        "세이프가드", "긴급수입제한", "safeguard", "safeguard duty",
    ],
    "EXPORT_CONTROL": [
        "수출통제", "전략물자", "엔티티 리스트", "제재대상",
        "export control", "export controls", "entity list",
        "sanctions", "sanctioned entity", "uflpa",
        "bureau of industry and security", "bis rule",
    ],
    "CBAM": [
        "cbam", "탄소국경", "탄소국경조정", "carbon border adjustment",
    ],
}

CONTEXTUAL_RULES = [
    ("수입", ["규제", "제한", "금지", "쿼터", "조사", "허가", "장벽"]),
    ("수출", ["통제", "규제", "제한", "금지", "허가", "관리", "제재"]),
    ("무역", ["장벽", "분쟁", "구제", "제재", "협상", "규제", "제한"]),
    ("통상", ["협상", "분쟁", "조약", "협정", "제재", "장벽", "규제"]),
    ("import", ["restriction", "ban", "quota", "investigation", "licensing", "barrier"]),
    ("export", ["control", "restriction", "ban", "licensing", "sanction"]),
    ("trade", ["barrier", "dispute", "remedy", "restriction", "sanction", "negotiation"]),
]

POLICY_INSTITUTION_TERMS = [
    "ustr", "united states trade representative", "usitc",
    "international trade commission", "bureau of industry and security",
    "world trade organization", "wto", "dg trade",
    "미국 무역대표부", "미 무역대표부", "미국 상무부", "미 상무부",
    "산업안보국", "무역위원회",
]

GENERIC_NOISE_TERMS = [
    # markets / finance
    "주가", "목표주가", "시가총액", "증시", "환율", "외환", "코스피", "코스닥",
    "earnings", "stock price", "price target", "market cap", "exchange rate",
    # employment / welfare / local administration
    "고용", "취업", "실업", "건강보험", "건보", "복지", "지방세", "체납",
    "employment", "unemployment", "health insurance",
    # lifestyle / sports / entertainment
    "kbo", "프로야구", "연예", "여행", "관광", "날씨", "폭염",
    "sports", "entertainment", "travel", "tourism", "weather",
    # editorials / columns
    "칼럼", "기고", "사설", "오피니언",
    # local / unrelated project noise
    "마을태양광", "발전소 준공", "자원순환 정책 수출", "농촌진흥", "한돈산업",
]

LOW_VALUE_PATTERNS = [
    r"\b실적\b",
    r"\b매출\b",
    r"\b영업이익\b",
    r"\b수출\s*(증가|감소|회복|호조|실적|전망)",
    r"\b수입\s*(증가|감소|물가|가격|실적|전망)",
    r"\btrade\s*(volume|growth|data|statistics)\b",
    r"\bexport\s*(growth|data|performance|outlook)\b",
    r"\bimport\s*(growth|data|performance|outlook)\b",
]

PRODUCT_TERMS = [
    "semiconductor", "반도체", "chip", "chips",
    "smartphone", "스마트폰", "mobile", "휴대폰",
    "display", "oled", "디스플레이",
    "battery", "batteries", "배터리",
    "steel", "철강", "aluminum", "aluminium", "알루미늄",
    "copper", "구리", "polysilicon", "폴리실리콘",
    "solar", "태양광", "rare earth", "희토류",
]

SAMSUNG_TERMS = ["samsung", "삼성전자", "삼성", "galaxy", "갤럭시"]


# =============================================================================
# UTILITIES
# =============================================================================

def log(msg: str) -> None:
    print(f"[{datetime.now():%Y-%m-%d %H:%M:%S}] {msg}")


def clean(v) -> str:
    if v is None:
        return ""
    try:
        if pd.isna(v):
            return ""
    except Exception:
        pass
    return re.sub(r"\s+", " ", str(v)).strip()


def text_norm(v) -> str:
    return clean(v).lower()


def normalize_title(v) -> str:
    s = text_norm(v)
    s = re.sub(r"\[[^\]]*\]", " ", s)
    s = re.sub(r"\([^\)]*\)", " ", s)
    s = re.sub(r"[^0-9a-z가-힣一-龥ぁ-ゔァ-ヴー\s]", " ", s)
    return re.sub(r"\s+", " ", s).strip()


def normalize_url(v) -> str:
    u = clean(v)
    if not u.startswith(("http://", "https://")):
        return ""
    try:
        p = urlparse(u)
        query = []
        for k, value in parse_qsl(p.query, keep_blank_values=True):
            if k.lower() not in {
                "utm_source", "utm_medium", "utm_campaign",
                "utm_term", "utm_content", "gclid", "fbclid",
            }:
                query.append((k, value))
        return urlunparse(
            (
                p.scheme.lower(),
                p.netloc.lower(),
                p.path.rstrip("/"),
                "",
                urlencode(query),
                "",
            )
        )
    except Exception:
        return u.lower()


def domain_of(url: str) -> str:
    try:
        return urlparse(clean(url)).netloc.lower()
    except Exception:
        return ""


def first_existing(df: pd.DataFrame, aliases: list[str]):
    index = {str(c).strip().lower(): c for c in df.columns}
    for alias in aliases:
        if alias.lower() in index:
            return index[alias.lower()]
    return None


def article_evidence(row: pd.Series) -> str:
    """Never include InputKeyword here."""
    return " ".join(
        [
            clean(row.get("Headline", "")),
            clean(row.get("Summary", "")),
            clean(row.get("Publisher", "")),
            clean(row.get("Source", "")),
        ]
    ).lower()


# =============================================================================
# INPUT NORMALIZATION
# =============================================================================

COLUMN_ALIASES = {
    "Date": ["Date", "date", "published", "published_at", "pubDate", "pub_date"],
    "CollectedAt": ["CollectedAt", "collected_at", "collected", "crawl_time"],
    "Headline": ["Headline", "headline", "title", "Title", "제목"],
    "Summary": ["Summary", "summary", "description", "Description", "snippet"],
    "URL": ["URL", "url", "link", "Link"],
    "OriginalURL": [
        "OriginalURL", "original_url", "resolved_url", "ResolvedURL",
        "OriginalURLCandidate", "BestLinkURL",
    ],
    "Source": ["Source", "source", "feed", "source_url"],
    "Publisher": ["Publisher", "publisher", "Agency", "agency", "media"],
    "InputKeyword": ["InputKeyword", "input_keyword", "Keyword", "keyword"],
}


def standardize_input(df: pd.DataFrame, source_file: str) -> pd.DataFrame:
    out = pd.DataFrame(index=df.index)

    for target, aliases in COLUMN_ALIASES.items():
        col = first_existing(df, aliases)
        out[target] = df[col] if col else ""

    out["InputFile"] = source_file
    out["Date"] = pd.to_datetime(out["Date"], errors="coerce")
    out["CollectedAt"] = pd.to_datetime(out["CollectedAt"], errors="coerce")

    for c in [
        "Headline", "Summary", "URL", "OriginalURL",
        "Source", "Publisher", "InputKeyword", "InputFile",
    ]:
        out[c] = out[c].fillna("").astype(str)

    return out


def load_inputs() -> pd.DataFrame:
    frames = []

    for path in INPUT_FILES:
        if not path.exists():
            log(f"INPUT MISSING: {path.name}")
            continue

        try:
            raw = pd.read_excel(path, engine="openpyxl")
        except Exception as exc:
            log(f"INPUT READ FAIL: {path.name} / {type(exc).__name__}: {exc}")
            continue

        std = standardize_input(raw, path.name)
        frames.append(std)
        log(f"LOAD {path.name}: {len(std)}")

    if not frames:
        return pd.DataFrame(columns=list(COLUMN_ALIASES) + ["InputFile"])

    df = pd.concat(frames, ignore_index=True, sort=False)
    log(f"LOAD TOTAL: {len(df)}")
    return df


# =============================================================================
# DATE FILTER
# =============================================================================

def filter_recent(df: pd.DataFrame, hours: int) -> tuple[pd.DataFrame, pd.DataFrame]:
    if df.empty:
        return df, df.copy()

    now = pd.Timestamp(datetime.now())
    cutoff = now - pd.Timedelta(hours=hours)

    work = df.copy()
    work["ReportDate"] = pd.to_datetime(work["Date"], errors="coerce")

    keep = (
        work["ReportDate"].notna()
        & (work["ReportDate"] >= cutoff)
        & (work["ReportDate"] <= now + pd.Timedelta(hours=2))
    )

    excluded = work[~keep].copy()
    excluded["RejectReason"] = "OUTSIDE_REPORT_WINDOW_OR_NO_DATE"

    result = work[keep].copy().reset_index(drop=True)

    log(
        f"STRICT {hours}h FILTER: {len(df)} -> {len(result)} "
        f"/ removed={len(excluded)}"
    )

    if not result.empty:
        log(
            f"DATE RANGE: {result['ReportDate'].min()} "
            f"~ {result['ReportDate'].max()}"
        )

    return result, excluded


# =============================================================================
# URL HANDLING
# =============================================================================

def choose_best_url(row: pd.Series) -> str:
    for col in ["OriginalURL", "URL"]:
        u = normalize_url(row.get(col, ""))
        if u:
            return u
    return ""


def looks_google_redirect(url: str) -> bool:
    d = domain_of(url)
    return d.endswith("google.com") or d.endswith("google.co.kr") or d.endswith("news.google.com")


def resolve_url(url: str) -> str:
    if not url or not looks_google_redirect(url):
        return url

    try:
        r = requests.get(
            url,
            timeout=URL_TIMEOUT,
            allow_redirects=True,
            headers={"User-Agent": "Mozilla/5.0"},
        )
        final = normalize_url(r.url)
        if final and not looks_google_redirect(final):
            return final
    except Exception:
        pass

    return url


def prepare_urls(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df

    work = df.copy()
    work["BestURL"] = work.apply(choose_best_url, axis=1)
    work["URLStatus"] = work["BestURL"].apply(
        lambda u: "GOOGLE_UNRESOLVED" if looks_google_redirect(u) else ("ORIGINAL" if u else "MISSING")
    )

    if RESOLVE_ORIGINAL_URL:
        unresolved_idx = work.index[work["URLStatus"].eq("GOOGLE_UNRESOLVED")].tolist()
        unresolved_idx = unresolved_idx[:URL_RESOLVE_LIMIT]

        for n, idx in enumerate(unresolved_idx, 1):
            old = work.at[idx, "BestURL"]
            new = resolve_url(old)
            work.at[idx, "BestURL"] = new
            work.at[idx, "URLStatus"] = (
                "RESOLVED" if new and not looks_google_redirect(new) else "GOOGLE_UNRESOLVED"
            )

            if n % 25 == 0:
                log(f"URL RESOLVE: {n}/{len(unresolved_idx)}")

    return work


# =============================================================================
# RELEVANCE ENGINE
# =============================================================================

@dataclass
class GateResult:
    keep: bool
    gate: str
    issue: str
    reason: str
    score: int


def strong_signal(text: str) -> tuple[str, list[str]]:
    hits = []

    for issue, terms in STRONG_RULES.items():
        found = [t for t in terms if t in text]
        if found:
            hits.extend(found)
            return issue, found

    return "", hits


def contextual_signal(text: str) -> tuple[bool, str]:
    for lead, partners in CONTEXTUAL_RULES:
        if lead in text:
            for partner in partners:
                if partner in text:
                    return True, f"{lead}+{partner}"

    # Institution alone is not enough. It must coexist with trade-policy language.
    institution = next((x for x in POLICY_INSTITUTION_TERMS if x in text), "")
    if institution:
        policy_words = [
            "tariff", "customs", "trade restriction", "export control",
            "import restriction", "trade remedy", "market access",
            "관세", "통관", "수입규제", "수출통제", "무역장벽", "시장접근",
        ]
        policy = next((x for x in policy_words if x in text), "")
        if policy:
            return True, f"{institution}+{policy}"

    return False, ""


def generic_noise(text: str) -> str:
    for term in GENERIC_NOISE_TERMS:
        if term in text:
            return term

    for pattern in LOW_VALUE_PATTERNS:
        if re.search(pattern, text, flags=re.I):
            return pattern

    return ""


def samsung_signal(text: str) -> tuple[bool, list[str]]:
    hits = [x for x in SAMSUNG_TERMS if x in text]
    product_hits = [x for x in PRODUCT_TERMS if x in text]
    return bool(hits or product_hits), list(dict.fromkeys(hits + product_hits))


def evaluate_row(row: pd.Series) -> GateResult:
    text = article_evidence(row)

    issue, strong_hits = strong_signal(text)
    noise = generic_noise(text)

    # Explicit customs evidence overrides generic-noise words.
    if issue:
        samsung, samsung_hits = samsung_signal(text)
        score = 80
        if samsung:
            score += 10
        if len(strong_hits) >= 2:
            score += 5
        score = min(score, 100)
        return GateResult(
            True,
            "CORE",
            issue,
            "; ".join(strong_hits + samsung_hits[:4]),
            score,
        )

    # No explicit customs signal -> noise can reject immediately.
    if noise:
        return GateResult(False, "REJECT", "", f"GENERIC_NOISE:{noise}", 0)

    contextual, context_reason = contextual_signal(text)
    if contextual:
        samsung, samsung_hits = samsung_signal(text)
        score = 55
        if samsung:
            score += 10
        return GateResult(
            True,
            "CONTEXTUAL",
            "TRADE_POLICY",
            "; ".join([context_reason] + samsung_hits[:4]),
            min(score, 75),
        )

    return GateResult(False, "REJECT", "", "NO_CUSTOMS_TRADE_EVIDENCE", 0)


def apply_relevance(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    if df.empty:
        return df, df.copy()

    rows = []
    rejects = []

    for _, row in df.iterrows():
        r = row.copy()
        result = evaluate_row(r)

        r["CandidateGate"] = result.gate
        r["IssueKey"] = result.issue
        r["GateReason"] = result.reason
        r["RuleScore"] = result.score

        if result.keep:
            rows.append(r)
        else:
            r["RejectReason"] = result.reason
            rejects.append(r)

    kept = pd.DataFrame(rows)
    excluded = pd.DataFrame(rejects)

    if kept.empty:
        kept = df.iloc[0:0].copy()

    if excluded.empty:
        excluded = df.iloc[0:0].copy()

    core = int((kept.get("CandidateGate", pd.Series(dtype=str)) == "CORE").sum())
    contextual = int((kept.get("CandidateGate", pd.Series(dtype=str)) == "CONTEXTUAL").sum())

    log(
        f"RELEVANCE: {len(df)} -> {len(kept)} "
        f"/ CORE={core} / CONTEXTUAL={contextual} / rejected={len(excluded)}"
    )

    return kept.reset_index(drop=True), excluded.reset_index(drop=True)


# =============================================================================
# DEDUPLICATION
# =============================================================================

def title_key(row: pd.Series) -> str:
    title = normalize_title(row.get("Headline", ""))
    publisher = text_norm(row.get("Publisher", ""))
    return f"{publisher}|{title}" if title else ""


def global_title_key(row: pd.Series) -> str:
    return normalize_title(row.get("Headline", ""))


def dedup_current(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    if df.empty:
        return df, df.copy()

    work = df.copy()
    work["_url_key"] = work["BestURL"].map(normalize_url)
    work["_title_key"] = work.apply(title_key, axis=1)
    work["_global_title"] = work.apply(global_title_key, axis=1)

    work = work.sort_values(
        ["RuleScore", "ReportDate"],
        ascending=[False, False],
        kind="stable",
    )

    keep_idx = []
    dup_idx = []
    seen_urls = set()
    seen_titles = set()

    for idx, row in work.iterrows():
        u = clean(row["_url_key"])
        t = clean(row["_title_key"])

        is_dup = False

        if u and not looks_google_redirect(u) and u in seen_urls:
            is_dup = True

        if t and t in seen_titles:
            is_dup = True

        if is_dup:
            dup_idx.append(idx)
            continue

        keep_idx.append(idx)
        if u and not looks_google_redirect(u):
            seen_urls.add(u)
        if t:
            seen_titles.add(t)

    kept = work.loc[keep_idx].copy()
    dup = work.loc[dup_idx].copy()
    if not dup.empty:
        dup["RejectReason"] = "CURRENT_DUPLICATE"

    kept = kept.drop(columns=["_url_key", "_title_key", "_global_title"], errors="ignore")
    dup = dup.drop(columns=["_url_key", "_title_key", "_global_title"], errors="ignore")

    log(f"CURRENT DEDUP: {len(work)} -> {len(kept)} / removed={len(dup)}")
    return kept.reset_index(drop=True), dup.reset_index(drop=True)


# =============================================================================
# EVENT CLUSTERING
# =============================================================================

POLICY_ANCHORS = [
    "section 232", "section 301", "232조", "301조",
    "반덤핑", "anti-dumping", "antidumping",
    "상계관세", "countervailing", "세이프가드", "safeguard",
    "수출통제", "export control", "entity list", "cbam",
    "상호관세", "reciprocal tariff",
]

COUNTRY_TERMS = [
    "미국", "중국", "한국", "일본", "eu", "유럽연합", "멕시코", "베트남",
    "인도", "캐나다", "브라질", "uk", "영국", "폴란드",
]


def event_key(row: pd.Series) -> str:
    text = article_evidence(row)
    issue = clean(row.get("IssueKey", "")) or "TRADE_POLICY"

    policy = next((x for x in POLICY_ANCHORS if x in text), "")
    product = next((x for x in PRODUCT_TERMS if x in text), "")
    country = next((x for x in COUNTRY_TERMS if x in text), "")

    pct_match = re.search(r"(?<!\d)(\d{1,3}(?:\.\d+)?)\s*%", text)
    pct = f"{pct_match.group(1)}%" if pct_match else ""

    # Good event signature when we have at least 2 useful anchors.
    anchors = [x for x in [policy, product, country, pct] if x]
    if len(anchors) >= 2:
        return "|".join([issue] + anchors)

    # Conservative fallback: do not over-cluster unrelated stories.
    title = normalize_title(row.get("Headline", ""))
    tokens = title.split()[:10]
    return f"{issue}|{' '.join(tokens)}"


def cluster_events(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    if df.empty:
        return df, df.copy()

    work = df.copy()
    work["EventKey"] = work.apply(event_key, axis=1)
    work = work.sort_values(
        ["RuleScore", "ReportDate"],
        ascending=[False, False],
        kind="stable",
    )

    keep = []
    audit = []

    for key, group in work.groupby("EventKey", sort=False):
        group = group.copy()
        group["ClusterSize"] = len(group)
        group["ClusterRank"] = range(1, len(group) + 1)

        keep_group = group.head(MAX_PER_CLUSTER)
        drop_group = group.iloc[MAX_PER_CLUSTER:].copy()

        keep.extend(keep_group.to_dict("records"))

        if not drop_group.empty:
            drop_group["RejectReason"] = "EVENT_CLUSTER_DUPLICATE"
            audit.extend(drop_group.to_dict("records"))

    kept = pd.DataFrame(keep)
    dropped = pd.DataFrame(audit)

    if kept.empty:
        kept = work.iloc[0:0].copy()
    if dropped.empty:
        dropped = work.iloc[0:0].copy()

    log(
        f"EVENT CLUSTER: {len(work)} -> {len(kept)} "
        f"/ removed={len(dropped)} / keep_per_cluster={MAX_PER_CLUSTER}"
    )

    return kept.reset_index(drop=True), dropped.reset_index(drop=True)


# =============================================================================
# CLEAN CUMULATIVE
# =============================================================================

def archive_legacy_cumulative() -> None:
    if not CUMULATIVE_FILE.exists():
        return

    try:
        old = pd.read_excel(CUMULATIVE_FILE, nrows=5, engine="openpyxl")
    except Exception:
        return

    valid_engine = (
        "EngineVersion" in old.columns
        and old["EngineVersion"].astype(str).eq(ENGINE_VERSION).any()
    )

    if valid_engine or not RESET_LEGACY_CUMULATIVE:
        return

    archive_dir = BASE_DIR / "archive"
    archive_dir.mkdir(parents=True, exist_ok=True)

    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    dest = archive_dir / f"3-2.news_cumulative_LEGACY_{stamp}.xlsx"

    try:
        shutil.copy2(CUMULATIVE_FILE, dest)
        CUMULATIVE_FILE.unlink()
        log(f"LEGACY CUMULATIVE RESET: archived -> {dest}")
    except Exception as exc:
        log(f"LEGACY CUMULATIVE RESET WARN: {exc}")


def load_clean_cumulative() -> pd.DataFrame:
    archive_legacy_cumulative()

    if not CUMULATIVE_FILE.exists():
        return pd.DataFrame()

    try:
        old = pd.read_excel(CUMULATIVE_FILE, engine="openpyxl")
    except Exception as exc:
        log(f"CUMULATIVE READ WARN: {exc}")
        return pd.DataFrame()

    if "EngineVersion" not in old.columns:
        return pd.DataFrame()

    return old[old["EngineVersion"].astype(str).eq(ENGINE_VERSION)].copy()


def historical_dedup(df: pd.DataFrame, old: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    if df.empty or old.empty:
        return df, df.iloc[0:0].copy()

    old_urls = {
        normalize_url(x)
        for x in old.get("BestURL", pd.Series(dtype=str))
        if normalize_url(x) and not looks_google_redirect(normalize_url(x))
    }

    old_titles = {
        normalize_title(x)
        for x in old.get("Headline", pd.Series(dtype=str))
        if normalize_title(x)
    }

    keep = []
    dup = []

    for _, row in df.iterrows():
        u = normalize_url(row.get("BestURL", ""))
        t = normalize_title(row.get("Headline", ""))

        is_dup = (
            (u and not looks_google_redirect(u) and u in old_urls)
            or (t and t in old_titles)
        )

        if is_dup:
            r = row.copy()
            r["RejectReason"] = "HISTORICAL_DUPLICATE"
            dup.append(r)
        else:
            keep.append(row)

    kept = pd.DataFrame(keep)
    excluded = pd.DataFrame(dup)

    if kept.empty:
        kept = df.iloc[0:0].copy()
    if excluded.empty:
        excluded = df.iloc[0:0].copy()

    log(f"HISTORICAL DEDUP: {len(df)} -> {len(kept)} / removed={len(excluded)}")
    return kept.reset_index(drop=True), excluded.reset_index(drop=True)


# =============================================================================
# FINAL RANKING
# =============================================================================

def source_score(row: pd.Series) -> int:
    d = domain_of(row.get("BestURL", ""))

    if any(
        x in d
        for x in [
            ".gov", ".go.kr", "europa.eu", "wto.org",
            "ustr.gov", "cbp.gov", "usitc.gov",
        ]
    ):
        return 10

    if clean(row.get("URLStatus", "")) in {"ORIGINAL", "RESOLVED"}:
        return 5

    return 0


def final_score(row: pd.Series) -> int:
    base = int(row.get("RuleScore", 0) or 0)
    return min(100, base + source_score(row))


def finalize(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        cols = [
            "Date", "CollectedAt", "Headline", "Summary", "BestURL",
            "Publisher", "Source", "InputKeyword", "InputFile",
            "CandidateGate", "IssueKey", "GateReason", "RuleScore",
            "FinalScore", "EventKey", "ClusterSize", "ClusterRank",
            "URLStatus", "EngineVersion",
        ]
        return pd.DataFrame(columns=cols)

    work = df.copy()
    work["FinalScore"] = work.apply(final_score, axis=1)
    work["EngineVersion"] = ENGINE_VERSION

    work = work.sort_values(
        ["FinalScore", "CandidateGate", "ReportDate"],
        ascending=[False, True, False],
        kind="stable",
    ).head(MAX_OUTPUT).copy()

    work["Priority"] = range(1, len(work) + 1)

    cols = [
        "Priority",
        "Date",
        "CollectedAt",
        "Headline",
        "Summary",
        "BestURL",
        "URLStatus",
        "Publisher",
        "Source",
        "InputKeyword",
        "InputFile",
        "CandidateGate",
        "IssueKey",
        "GateReason",
        "RuleScore",
        "FinalScore",
        "EventKey",
        "ClusterSize",
        "ClusterRank",
        "EngineVersion",
    ]

    for c in cols:
        if c not in work.columns:
            work[c] = ""

    return work[cols].reset_index(drop=True)


def update_cumulative(old: pd.DataFrame, final_df: pd.DataFrame) -> pd.DataFrame:
    if final_df.empty:
        return old.copy()

    combined = pd.concat([old, final_df], ignore_index=True, sort=False)

    combined["_url_key"] = combined["BestURL"].astype(str).map(normalize_url)
    combined["_title_key"] = combined["Headline"].astype(str).map(normalize_title)

    combined = combined.sort_values("Date", ascending=False, kind="stable")

    # Title is the safest cross-source key.
    combined = combined.drop_duplicates("_title_key", keep="first")

    combined = combined.drop(columns=["_url_key", "_title_key"], errors="ignore")
    return combined.reset_index(drop=True)


# =============================================================================
# OUTPUT
# =============================================================================

def safe_write(path: Path, df: pd.DataFrame) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    try:
        df.to_excel(path, index=False)
    except PermissionError:
        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        alt = path.with_name(f"{path.stem}_{stamp}{path.suffix}")
        df.to_excel(alt, index=False)
        log(f"FILE LOCKED: {path.name} -> saved {alt.name}")


# =============================================================================
# MAIN
# =============================================================================

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="GTI STEP3-2 REBUILD")
    p.add_argument("--hours", type=int, default=REPORT_HOURS)
    p.add_argument("--max-output", type=int, default=MAX_OUTPUT)
    return p.parse_args()


def main() -> int:
    global MAX_OUTPUT

    args = parse_args()
    MAX_OUTPUT = args.max_output

    log("=" * 80)
    log("GTI STEP3-2 REBUILD v1 START")
    log("=" * 80)

    df = load_inputs()

    if df.empty:
        log("NO INPUT DATA")
        safe_write(OUTPUT_FILE, finalize(df))
        return 0

    all_excluded = []

    # 1. Strict report window
    df, excluded = filter_recent(df, args.hours)
    all_excluded.append(excluded)

    # 2. URL selection / lightweight recovery
    df = prepare_urls(df)

    # 3. Evidence-based relevance
    df, excluded = apply_relevance(df)
    all_excluded.append(excluded)

    # 4. Same-run duplicates
    df, excluded = dedup_current(df)
    all_excluded.append(excluded)

    # 5. Same policy event clustering
    df, cluster_excluded = cluster_events(df)
    all_excluded.append(cluster_excluded)

    # 6. Clean cumulative only
    old = load_clean_cumulative()
    log(f"CLEAN CUMULATIVE LOAD: {len(old)}")

    df, excluded = historical_dedup(df, old)
    all_excluded.append(excluded)

    # 7. Final ranking
    final_df = finalize(df)

    # File-boundary 24h safety check
    if not final_df.empty:
        now = pd.Timestamp(datetime.now())
        cutoff = now - pd.Timedelta(hours=args.hours)
        dates = pd.to_datetime(final_df["Date"], errors="coerce")
        final_df = final_df[
            dates.notna()
            & (dates >= cutoff)
            & (dates <= now + pd.Timedelta(hours=2))
        ].copy().reset_index(drop=True)

        final_df["Priority"] = range(1, len(final_df) + 1)

    # 8. Cumulative
    cumulative_df = update_cumulative(old, final_df)

    # 9. Audit/excluded
    excluded_frames = [x for x in all_excluded if x is not None and not x.empty]
    excluded_df = (
        pd.concat(excluded_frames, ignore_index=True, sort=False)
        if excluded_frames
        else pd.DataFrame()
    )

    safe_write(OUTPUT_FILE, final_df)
    safe_write(CUMULATIVE_FILE, cumulative_df)
    safe_write(EXCLUDED_FILE, excluded_df)
    safe_write(CLUSTER_AUDIT_FILE, cluster_excluded)

    log("-" * 80)
    log(f"FINAL CANDIDATES: {len(final_df)}")
    if not final_df.empty:
        log(
            "FINAL GATE: "
            + str(final_df["CandidateGate"].value_counts().to_dict())
        )
        log(
            "FINAL ISSUE: "
            + str(final_df["IssueKey"].value_counts().head(10).to_dict())
        )
    log(f"CUMULATIVE: {len(cumulative_df)}")
    log(f"EXCLUDED/AUDIT: {len(excluded_df)}")
    log(f"SAVE: {OUTPUT_FILE}")
    log("=" * 80)
    log("GTI STEP3-2 REBUILD v1 DONE")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
